name: 'Drupal Regression'
description: 'Using Drupal regression API.'
inputs:
  url:
    description: 'Test URL, to check existing data against'
    required: true
  work_dir:
    description: 'The work dir to save regressions in. - defaults to drupal-regression'
    default: 'drupal-regression'
outputs:
  diff:
    description: 'The difference, if any'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.work_dir }}
