name: 'Drupal Regression'

on:
  workflow_call:
    inputs:
      PLATFORMSH_ID:
        required: true
        type: string
      WORK_DIR:
        type: string
        default: './drupal-regression'
    secrets:
      PLATFORMSH_KEY:
        required: true

jobs:
  drupal-regression:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: drupal-regression
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :robot: :speech_balloon: `checking for drupal-regression - this can take a few minutes..`
          edit-mode: replace
          reactions: ${{ steps.drupal-regression.outputs.reactions }}
      - uses: actions/checkout@v1
      - uses: reload/action-platformsh-url@main
        id: platformsh_url
        with:
          PLATFORMSH_ID: ${{ inputs.PLATFORMSH_ID }}
          PLATFORMSH_KEY: ${{ secrets.PLATFORMSH_KEY }}
      - name: Drupal Regression
        id: drupal-regression
        uses: reload/action-drupal-regression@main
        with:
          url: ${{ steps.platformsh_url.outputs.url }}
          work_dir: ${{ inputs.WORK_DIR }}
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: drupal-regression
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc2.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.drupal-regression.outputs.message }}
          edit-mode: replace
          reactions: ${{ steps.drupal-regression.outputs.reactions }}
      - name: Check for regression fail
        if: ${{ steps.drupal-regression.outputs.status == 'fail' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Drupal Regression failed. See comment, or "Drupal Regression" above.')
